# Generated by Django 4.0.5 on 2022-06-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='health_officer',
            new_name='health_officers',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='police_officer',
            new_name='police_officers',
        ),
    ]
