# Generated by Django 4.0.5 on 2022-06-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_rename_health_officer_neighborhood_health_officers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='health_officers',
            new_name='health_centers',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='police_officers',
            new_name='police_authorities',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hoodapp.neighborhood'),
        ),
    ]
