# Generated by Django 4.0.5 on 2022-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_rename_health_officers_neighborhood_health_centers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='health_centers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='health_contact',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_authorities',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_contact',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
