# Generated by Django 4.0.5 on 2022-06-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_alter_neighborhood_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='admin',
        ),
    ]
